# see CONTRIBUTING.md
---
version: '3'
services:
  mysql-perfschema:
    image: ${MYSQL_IMAGE:-percona/percona-server}
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command:
      - --log-output=NONE
  mysql-slowlog:
    image: ${MYSQL_IMAGE:-percona/percona-server}
    ports:
      - 127.0.0.1:3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command:
      - --log-output=FILE
      - --slow_query_log=ON
      - --slow_query_log_file=/tmp/pmm-test/slow.log
      - --long_query_time=0
    volumes:
      - /tmp/pmm-test:/tmp/pmm-test
  postgresql:
    image: ${POSTGRESQL_IMAGE:-postgres}
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=root
  mongodb:
    image: ${MONGODB_IMAGE:-percona/percona-server-mongodb}
    ports:
      - 127.0.0.1:27017:27017
